# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    increment_build_number(xcodeproj: "JavaZone.xcodeproj")
    commit_version_bump(xcodeproj: "JavaZone.xcodeproj")
    add_git_tag
    push_to_git_remote
    get_provisioning_profile(app_identifier: "net.chrissearle.incogito.JavaZone")
    get_provisioning_profile(app_identifier: "net.chrissearle.incogito.JavaZone.Duke")
    build_app(scheme: "JavaZone")
    upload_to_testflight
    slack(message: "Beta build uploaded")
  end
end
